### ISSUE TITLE
Using of Enums as Field Values not possible

### ISSUE THREAD

**Issue by finanzer** [dlsc-software-consulting-gmbh/PreferencesFX#10]
The using of enums as Values for Settings and Setting values and Setting selections is not possible, because the StorageHandler converts all stored values to Object and not to the type of the Setting value.

Example:

Create Setting:

```
    private ObjectProperty<MyEnum> myEnumSettingValue = new SimpleObjectProperty<>(MyEnum.FIRST);
    private SingleSelectionField<MyEnum> myEnumControl = Field.ofSingleSelectionType(Arrays.asList(MyEnum.values()), 0).render(new RadioButtonControl<>());
```

Create Preference:

```
        preferencesFx = PreferencesFx.of(MyApplication.class,
                Category.of("Category",
                        Group.of("Group",
                                Setting.of("My Enum", myEnumControl , myEnumSettingValue)
                        )
                )
        );
```

Reading of value of myEnumSettingValuewith 

MyEnum myEnum = myEnumSettingValue.get()

after creation of PreferencesFx results in a ClassCastException because there is no MyEnum in myEnumValue,. but a String with value "FIRST".

The reason is that StorageHandler reads in loadObject (line 176)  into Object and not into a MyEnum:

```
  public Object loadObject(String breadcrumb, Object defaultObject) {
    String serializedDefault = gson.toJson(defaultObject);
    String json = preferences.get(hash(breadcrumb), serializedDefault);
    return gson.fromJson(json, Object.class);
  }
```
The generic T at ObjectProperty will be infered to Object at runtime, so there is no Exception if the method setValue(T value) is called with a String.

My Workaround is to use an own implementation of SimpleObjectProperty that creates the correct enum value from the given string. I can't use here a more specific generic, because it would be result in ClassCastException too, when setValue() will be called.

```
public class SettingEnumObjectProperty<T> extends SimpleObjectProperty<T>
{
    private static final Object DEFAULT_BEAN = null;
    private static final String DEFAULT_NAME = "";

    private Class enumClass;

    /**
     * The constructor of {@code SettingEnumObjectProperty}
     *
     * @param initialValue
     *            the initial value of the wrapped value
     */
    public SettingEnumObjectProperty(T initialValue, Class<T> enumClass) {
        super(DEFAULT_BEAN, DEFAULT_NAME, initialValue);
        this.enumClass = enumClass;
    }

    /**
     * It's a little bit tricky because to runtime T will be infered to Object, so that passing a String is correct.
     * Here the false T will be converted to a correct enum value.
     */
    public void setValue(T value) {
        Object rawValue = value;
        if (rawValue instanceof String)
        {
            set((T)Enum.valueOf(enumClass, (String)rawValue));
        }
    }
}
```

**Comment by martinfrancois** [comment]
Hi @finanzer 

Thanks a lot for posting an issue about this, especially providing a workaround for all people that have the same issue 👍 We didn't think of this, which is why it's great having an open source community and people like you discovering things like that!

This is a problem indeed and I agree the workaround is not very pretty, but at the same time I can't think of a solution right now that would solve this issue universally... If you have a suggestion for a fix, please feel free to submit a PR!
