### ISSUE TITLE
Cannot use custom stylesheets on dialog

### ISSUE THREAD

**Issue by SamCarlberg** [dlsc-software-consulting-gmbh/PreferencesFX#11]
Dialogs created with `PreferencesFx.show()` cannot have their stylesheets set. Applications with custom stylesheets are unable to use anything but the default Modena styles on preferences dialogs

**Comment by martinfrancois** [comment]
Hi @SamCarlberg 

Good suggestion! I agree. Feel free to submit a PR to fix this issue and we will happily merge it.

Thanks! 👍
