### ISSUE TITLE
UndoRedoBox Button colors

### ISSUE THREAD

**Issue by trixon** [dlsc-software-consulting-gmbh/PreferencesFX#150]
Black icons on dark gray are hard to read.

Is it possible to change the glyph colors of the buttons in the UndoRedoBox?
I'm not able to do it, they have no id or style class I can define.
I tried a sledge hammer change with
.glyph-font{
    -fx-text-fill: orange !important;
}
but that only changed the looking glass icon in the filter box.

**Comment by dlemmermann** [comment]
I have added the style class "undo-redo-box" to the container and "undo-button" and "redo-button" to the buttons.

**Comment by trixon** [comment]
Great, thanks!
