### ISSUE TITLE
Gradle build fails

### ISSUE THREAD

**Issue by Dansoftowner** [dlsc-software-consulting-gmbh/PreferencesFX#267]
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find de.jensd:fontawesomefx-commons:11.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/de/jensd/fontawesomefx-commons/11.0/fontawesomefx-commons-11.0.pom
       - https://repo.maven.apache.org/maven2/de/jensd/fontawesomefx-commons/11.0/fontawesomefx-commons-11.0.jar
       - https://jitpack.io/de/jensd/fontawesomefx-commons/11.0/fontawesomefx-commons-11.0.pom
       - https://jitpack.io/de/jensd/fontawesomefx-commons/11.0/fontawesomefx-commons-11.0.jar
       - https://dl.bintray.com/dukke/maven/de/jensd/fontawesomefx-commons/11.0/fontawesomefx-commons-11.0.pom
       - https://dl.bintray.com/dukke/maven/de/jensd/fontawesomefx-commons/11.0/fontawesomefx-commons-11.0.jar
       - http://sandec.bintray.com/repo/de/jensd/fontawesomefx-commons/11.0/fontawesomefx-commons-11.0.pom
       - http://sandec.bintray.com/repo/de/jensd/fontawesomefx-commons/11.0/fontawesomefx-commons-11.0.jar
       - https://raw.githubusercontent.com/terjedahl/junique/master/maven2/de/jensd/fontawesomefx-commons/11.0/fontawesomefx-commons-11.0.pom
       - https://raw.githubusercontent.com/terjedahl/junique/master/maven2/de/jensd/fontawesomefx-commons/11.0/fontawesomefx-commons-11.0.jar
     Required by:
         project : > com.dlsc.preferencesfx:preferencesfx-core:11.5.0
   > Could not find de.jensd:fontawesomefx-fontawesome:4.7.0-11.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/de/jensd/fontawesomefx-fontawesome/4.7.0-11/fontawesomefx-fontawesome-4.7.0-11.pom
       - https://repo.maven.apache.org/maven2/de/jensd/fontawesomefx-fontawesome/4.7.0-11/fontawesomefx-fontawesome-4.7.0-11.jar
       - https://jitpack.io/de/jensd/fontawesomefx-fontawesome/4.7.0-11/fontawesomefx-fontawesome-4.7.0-11.pom
       - https://jitpack.io/de/jensd/fontawesomefx-fontawesome/4.7.0-11/fontawesomefx-fontawesome-4.7.0-11.jar
       - https://dl.bintray.com/dukke/maven/de/jensd/fontawesomefx-fontawesome/4.7.0-11/fontawesomefx-fontawesome-4.7.0-11.pom
       - https://dl.bintray.com/dukke/maven/de/jensd/fontawesomefx-fontawesome/4.7.0-11/fontawesomefx-fontawesome-4.7.0-11.jar
       - http://sandec.bintray.com/repo/de/jensd/fontawesomefx-fontawesome/4.7.0-11/fontawesomefx-fontawesome-4.7.0-11.pom
       - http://sandec.bintray.com/repo/de/jensd/fontawesomefx-fontawesome/4.7.0-11/fontawesomefx-fontawesome-4.7.0-11.jar
       - https://raw.githubusercontent.com/terjedahl/junique/master/maven2/de/jensd/fontawesomefx-fontawesome/4.7.0-11/fontawesomefx-fontawesome-4.7.0-11.pom
       - https://raw.githubusercontent.com/terjedahl/junique/master/maven2/de/jensd/fontawesomefx-fontawesome/4.7.0-11/fontawesomefx-fontawesome-4.7.0-11.jar
     Required by:
         project : > com.dlsc.preferencesfx:preferencesfx-core:11.5.0

**Comment by ssinnorr** [comment]
Hey dude! 

I had the same problem, you just need to add "jcenter()" to your repositories in build.gradle file, like this:

`repositories {
    jcenter()
}`

**Comment by ckosmowski** [comment]
The n

> Hey dude!
> 
> I had the same problem, you just need to add "jcenter()" to your repositories in build.gradle file, like this:
> 
> `repositories { jcenter() }`

This is something that could have been mentioned in the Readme.md?! :-)
