### ISSUE TITLE
JDK17 illegal access due to reflective call into com.sun package

### ISSUE THREAD

**Issue by ghost** [dlsc-software-consulting-gmbh/PreferencesFX#380]
With the release of JDK17, all calls to the internal `com.sun` package are forbidden. In particular,  `com.sun.javafx.scene.ParentHelper.setTraversalEngine(...)` is inaccessible. This is caused by `ReflectionUtils.java` attempting to access the `ParentHelper` class, as per:

```
    public static void setTraversalEngine(Control control, Object engine) {
        try {
            Class<?> parentHelper = Class.forName("com.sun.javafx.scene.ParentHelper");
            Method method = parentHelper.getMethod("setTraversalEngine", Parent.class, engine.getClass());
            method.setAccessible(true);
            method.invoke(parentHelper, control, engine);
        } catch (IllegalAccessException | InvocationTargetException | NoSuchMethodException | ClassNotFoundException e) {
            throw new RuntimeException("Cannot set Traversal Engine");
        }
    }
```

The method is used  by`NotificationPaneSkin` to work around a focus issue, and `BreadCrumbBarSkin`.

**Comment by dlemmermann** [comment]
Was this more tightened in 17?

**Comment by ghost** [comment]
> Was this more tightened in 17?

Yes. JDK 16 had a command-line workaround, `--illegal-access=permit`, that was deprecated. The option is removed in JDK 17. I've logged a bug against ControlsFX, which is the source of the problem that manifests itself in PreferencesFX.

**Comment by ghost** [comment]
See: https://github.com/controlsfx/controlsfx/issues/1394
