### ISSUE TITLE
TableView expands when adding new elements

### ISSUE THREAD

**Issue by ghost** [dlsc-software-consulting-gmbh/PreferencesFX#413]
**Replicate**
When adding new rows to a `TableView`, the table expands by two pixels.

1. Create a `SimpleTableControl` that extends `SimpleControl`.
1. Add a `TableView` and `ButtonBar` to the table control, both contained in a `VBox`.
1. Add an `Add` button to the `ButtonBar`.
1. Wire the `Add` button to add a new row to the `TableView`.
1. Create a `MapField` subclass of `Field` that renders using the `SimpleTableControl`.
1. Create a `Category` using the `MapField`.
1. Launch the GUI.
1. Click the `Add` button.

**Expected**
The `TableView` width remains fixed.

**Actual**
The `TableView` increases by two pixels.

**Work around**
Each time the button is clicked, resize the table:

``` java
table.setPrefWidth( table.getPrefWidth() - 2 );
```

**Additional details**
For implementation details see:

* [PreferencesController](https://github.com/DaveJarvis/keenwrite/blob/master/src/main/java/com/keenwrite/preferences/PreferencesController.java)
* [SimpleTableControl](https://github.com/DaveJarvis/keenwrite/blob/master/src/main/java/com/keenwrite/preferences/SimpleTableControl.java)

**Screen shots**
The screen shots show the button bar moving to the right and the horizontal scroll bar increasing in size:

![tableview-01](https://user-images.githubusercontent.com/2131950/147029208-c6163581-2099-4221-be74-43eeab8007d9.png)
![tableview-02](https://user-images.githubusercontent.com/2131950/147029209-170d8018-4259-4cb4-a4f2-d0edee91b7e1.png)
![tableview-03](https://user-images.githubusercontent.com/2131950/147029210-720eea55-045f-4bc5-aadb-97945ea8cfad.png)

**Comment by reikjarloekl** [comment]
This might have been fixed with #430 (change to preferencesfx/src/main/java/com/dlsc/preferencesfx/PreferencesFx.java).

**Comment by ghost** [comment]
Cool! I'll check it out when the next release is published.

**Comment by ghost** [comment]
This bug is fixed, but another bug now exists: #440 .
