### ISSUE TITLE
change visibility for Setting class

### ISSUE THREAD

**Issue by aldanchenko** [dlsc-software-consulting-gmbh/PreferencesFX#427]
Hi 👋,

Could you, please, guide me how to change visibility for `Setting` class?

For example, I need to change visibility of one of my components. In Swing or JavaFX I just can `setVisible(false)` or `setVisible(true)`. How can I do this with PreferencesFX?

Thank you for help!

Best regards,
Alex

**Comment by reikjarloekl** [comment]
@dlemmermann this should be closed also. It refers to the change merged with #429
