### ISSUE TITLE
When the last setting of a group is hidden with new visibility feature, the following group is drawn too close

### ISSUE THREAD

**Issue by reikjarloekl** [dlsc-software-consulting-gmbh/PreferencesFX#432]
Currently, the distance between the last element of a group and the first element (title or setting for groups without title) is implemented by setting the bottom margin of the last settings element in a group higher. Therefore, when the last element of a group is hidden, the layout breaks, i.e., the following group title is shown too close to the previous group:

![preferencesFx-layout](https://user-images.githubusercontent.com/839540/186879040-5e2ec9cf-5e7e-45ae-95bc-96ded77f5a7f.png)

**Comment by dlemmermann** [comment]
:-) Assigning you @reikjarloekl as I do not have time to look into this issue.

**Comment by reikjarloekl** [comment]
It's fixed already. =) Will open a PR in a minute.
