### ISSUE TITLE
List properties show history as modified on initial load

### ISSUE THREAD

**Issue by VirtualTim** [dlsc-software-consulting-gmbh/PreferencesFX#436]
`PreferencesFx.init()` directly calls `this.preferencesFxModel.loadSettingValues();`.
Slightly further down, the same function calls `this.preferencesFxDialog = new PreferencesFxDialog(this.preferencesFxModel, this.preferencesFxView);`, which calls `model.loadSettingValues();`, where `model` is the same object as the above `this.preferencesFxModel`.

This means that all settings are loaded twice.

This causes in particular with list properties (ie `SimpleListProperty`), as the two list loaded objects are not the same object, so this triggers change listeners.

I can't think of a good reason for this to be called twice. However I don't know which one would be the correct one to call.

**Comment by VirtualTim** [comment]
Pseudo stack-trace:

https://github.com/dlsc-software-consulting-gmbh/PreferencesFX/blob/4348c8f6e4097f49dea2fd98207303df369d6b4f/preferencesfx/src/main/java/com/dlsc/preferencesfx/PreferencesFx.java#L68-L70

https://github.com/dlsc-software-consulting-gmbh/PreferencesFX/blob/4348c8f6e4097f49dea2fd98207303df369d6b4f/preferencesfx/src/main/java/com/dlsc/preferencesfx/PreferencesFx.java#L92

https://github.com/dlsc-software-consulting-gmbh/PreferencesFX/blob/dec39ef49704bde5ab0d39c9e8b4f3fd2c2ca5ca/preferencesfx/src/main/java/com/dlsc/preferencesfx/view/PreferencesFxDialog.java#L53-L59

**Comment by psharma-gdal** [comment]
@dlemmermann : Could you please let me know when are you planning on publishing the next version? Is this possible soon? I am interested in above fix. Thanks.

**Comment by dlemmermann** [comment]
Release 11.12.0 is now out there.
