### ISSUE TITLE
Set default view/Show first subcategory

### ISSUE THREAD

**Issue by ArvidNy** [dlsc-software-consulting-gmbh/PreferencesFX#83]
I'm trying to add subcategories to the first tab, but I haven't been able to show the first subcategory directly. Is this possible with the current code? Since the main category is empty, it doesn't make sense for us to show that - I think that would only confuse our users.

![empty tab](https://user-images.githubusercontent.com/14236185/62459623-2e2e6480-b780-11e9-8ac6-99b618c64be2.png)

**Comment by martinfrancois** [comment]
Hi @ArvidNy 
That's a good point! We didn't really think of this, but this use case makes sense.

Maybe it would make sense to add a method like `setCategoryShown(category)` which changes the currently shown category to the one passed in as a parameter. Then, after showing the preferences you can call `setCategoryShown(category 1)`, which would make it look for the user as if it was the default.
I think this would be the best approach, but we have to pay attention if this happens fast enough that the user doesn't see the other category first and them the switch. If the switch would be noticeable to the user, I could imagine it would make more sense to have a method like `defaultCategory()` which can be used for chaining like `persistWindowState() `

Feel free to submit a PR, I think this would make a great addition!

**Comment by ArvidNy** [comment]
Sure, a method like `setCategoryShown(category)`, would be a great addition too! However, I gave it a try after I created this issue and found another approach where I could make an empty category always open the first subcategory. I'll create a PR for that branch, but I'm not sure if I will find the time to create one for a `setCategoryShown` method too.
